apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cnpg-cluster-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: hpa-postgres-cluster
  podMetricsEndpoints:
  - port: metrics
